<?php
/**
 * @file
 * semi_page.features.inc
 */

/**
 * Implements hook_node_info().
 */
function semi_page_node_info() {
  $items = array(
    'page' => array(
      'name' => t('Page'),
      'base' => 'node_content',
      'description' => t('Content type to add Semi pages.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
