<?php
/**
 * @file
 * semi_events.features.inc
 */

/**
 * Implements hook_node_info().
 */
function semi_events_node_info() {
  $items = array(
    'events' => array(
      'name' => t('Events'),
      'base' => 'node_content',
      'description' => t('Content type for adding events.'),
      'has_title' => '1',
      'title_label' => t('Name'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
